### ISSUE TITLE
how to change the location

### ISSUE THREAD

**Issue by xfce** [lhm0/rotating_display#3]
Hi 
I think it is default location is Freiburg, but when I change the location.txt. and country.txt, it does not work, seems still Freiburg ,de

How can i change the location to get the correct time and weather, thanks

**Comment by lhm0** [comment]
Hi,
I need to understand better, what exactly you are doing. Can you provide some background on the setup? Do you have a full rotating display running? Do you use the web interface for setting the parameters? Have you entered an APIKey? Enter the city and country, hit "update data" After 10 seconds or so, the current weather for your location should show up in the web interface. 
Best regards, Ludwin

**Comment by xfce** [comment]
Yes I have just redesign the display PCB, fellow  guide
And I have fixed the problem,  location.txt and countroy.txt is for weather, Time zone is defined in the myesp.cpp, must change both, after chage these,  works fine, thanks
bellow is some picture.
![1691914397224](https://github.com/lhm0/rotating_display/assets/6119479/bed0f281-3e07-4938-bb3d-1c34ed8636f9)
![1691914397187](https://github.com/lhm0/rotating_display/assets/6119479/b4673a11-0e33-4dd1-8ce1-9f573ca4b04f)
![1691914397198](https://github.com/lhm0/rotating_display/assets/6119479/be99ced3-6061-4ee8-9b8a-30c80255827d)
![1691914397209](https://github.com/lhm0/rotating_display/assets/6119479/21aa8c65-70a9-4772-a269-9c9f14005ff3)
