### ISSUE TITLE
How to design the PCB coil

### ISSUE THREAD

**Issue by xfce** [lhm0/rotating_display#4]
Hi @lhm0 ,
        About the PCB coil design, is there any design guide? If I want to use this in other porjects such as some wireless charge circuit

**Comment by lhm0** [comment]
﻿Hi (what is your name?),There is no design guide, unfortunately. I have taken the data from https://www.mikrocontroller.net/articles/Royer_Converter . Unfortunately, this article is in German.This is the table, which gives the design data of the coils:WicklungWindungszahlDrahtdurch-messer[mm]Durchmesser[mm]Induktivität[µH]Primär2x100,558070Steuer10,280---Sekundär130,556523For you reference, here is the translation into English:Wicklung -> coilWindungszahl -> number of turnsDrahtdurchmesser -> diameter of wireDurchmesser -> diameterInduktivität -> inductancePrimär -> primarySteuer -> control (feedback coil)Sekundär -> secondaryThere are many online calculators for flat coils. Here is one:translatorscafe.comPlease note, that the primary coil is a bifilar coil. It consists of two interleaved halfs.I hope this helps.Best regardsLudwinAm 15.08.2023 um 13:14 schrieb bi4wms ***@***.***>:﻿
Hi @lhm0 ,
About the PCB coil design, is there any design guide? If I want to use this in other porjects such as some wireless charge circuit
